### ISSUE TITLE
webpack babel 사용시 asinc / await 쓰면 에러

### ISSUE THREAD

**Issue by ho-1** [hanpaa/Frankly#6]
regeneratorRuntime is not defined

**Comment by ho-1** [comment]
https://andrew-flower.com/blog/Async-Await-with-React

**Comment by hanpaa** [comment]
core-js 3 쓰니까 됩니다

참고:

https://github.com/zloirock/core-js/blob/master/docs/2019-03-19-core-js-3-babel-and-a-look-into-the-future.md#babelruntime

https://tech.kakao.com/2020/12/01/frontend-growth-02/
